### ISSUE TITLE
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by gvenkat21** [philferriere/dlwin#41]
Hi,

I followed your tutorial and everything went fine. The CPU test went perfectly but when I `set THEANO_FLAGS=%THEANO_FLAGS_GPU%`, I got the following error:

```
(dlwin36) C:\Users\Gautam>python cpu_gpu_test.py
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\Gautam\Anaconda2\envs\dlwin36\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\Users\Gautam\Anaconda2\envs\dlwin36\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\Users\Gautam\Anaconda2\envs\dlwin36\lib\site-packages\theano\gpuarray\__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
GpuArrayException: Error loading library: 0
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 20.002000 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```

**Comment by gvenkat21** [comment]
Hi,

I solved the issue by looking at the following page: https://github.com/Theano/Theano/issues/6006

The problem was with pygpu. I `set DEVICE=cuda0` and `set GPUARRAY_CUDA_VERSION=80`. 

That solved the problem.

**Comment by cedoard** [comment]
Hi,
I have the same issue, I followed your instructions and set that environment variables. 
Right now I get a new error when I run `pygpu.test()`:

```
Traceback (most recent call last):
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/secarbone/miniconda3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/secarbone/miniconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/pygpu/tests/test_operations.py", line 4, in <module>
    from .support import (gen_gpuarray, context, SkipTest)
  File "/Users/secarbone/miniconda3/lib/python3.6/site-packages/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "/Library/Frameworks/CUDA.framework/CUDA": dlopen(/Library/Frameworks/CUDA.framework/CUDA, 5): image not found'
```


    ```ERROR: Failure: GpuArrayException (b'Could not load "/Library/Frameworks/CUDA.framework/CUDA": dlopen(/Library/Frameworks/CUDA.framework/CUDA, 5): image not found')```

My system is Mac Os High Sierra 10.13 with NVIDIA GeForce GT 330M. I installed _cuda 10.0.130_ and _cudnn 10.0_.
This is my _.theanorc_ file:

    [global]
    floatX = float32
    device = gpu
    force_device = True
    optimizer_including=cudnn
    
    [nvcc]
    fastmath = True
    
    [cuda]
    root=Users/secarbone/cuda
